version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:18.14.1
jobs:
  check_whitespace:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check for trailing newlines
          command: ./dev-scripts/check-trailing-newline
  check_exif_data:
    docker:
      - image: davidanson/exiftool:v13.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add bash git
      - run:
          name: Check EXIF data
          command: |
            export PATH="/extract/Image-ExifTool-13.10:${PATH}"

            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "On "${CIRCLE_BRANCH}" branch, checking all content files..."
              ./dev-scripts/check-exif-data ./content/
            else
              echo "On branch ${CIRCLE_BRANCH}, checking only changed files..."

              # Get changed files in content directory
              changed_files=$(git diff --name-only origin/master...HEAD | grep '^content/' || true)

              if [ -n "${changed_files}" ]; then
                echo "Changed files in content directory:"
                echo "${changed_files}"
                echo ""

                # Convert newline-separated list to space-separated arguments
                # shellcheck disable=SC2086
                ./dev-scripts/check-exif-data ${changed_files}
              else
                echo "No content files changed compared to master"
                echo "✅ SUCCESS: No content files to check"
              fi
            fi
  build:
    docker:
      - image: hugomods/hugo:0.147.5
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - resources-gen-v{{ .Environment.RESOURCES_CACHE_VERSION }}
      - run:
          name: Build site
          command: |
            hugo version
            if [[ "$CIRCLE_BRANCH" != "master" ]]; then
              export HUGO_ENV=dev
            fi
            hugo --minify
      - persist_to_workspace:
          root: ./
          paths:
            - dev-scripts
            - public
            - netlify.toml
            - .htmltest.yml
      - save_cache:
          key: resources-gen-v{{ .Environment.RESOURCES_CACHE_VERSION }}
          paths:
            - resources
  prettier:
    executor: node
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Check code formatting with prettier
          command: npx prettier --check .
  check_html:
    docker:
      - image: wjdp/htmltest:v0.17.0
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run htmltest
          command: htmltest
  publish_draft:
    docker:
      - image: cimg/node:18.14.1
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      # This is a hack to get rid of the <base> tag, which prevents the blog from rendering
      # properly on Netlify's draft URL because it hardcodes the weeks.mtlynch.io domain.
      - run:
          name: Remove base tag from generated HTML
          command: find public -name "*.html" -exec sed -i -e 's/<base[^>]*>//g' {} +
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli --save-dev
      - run:
          name: Deploy a live draft
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}"
  deploy:
    docker:
      - image: cimg/node:18.14.1
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli --save-dev
      - run:
          name: Deploy to production
          command: ./node_modules/.bin/netlify deploy --dir=public --site="${NETLIFY_SITE_ID}" --prod
workflows:
  version: 2
  test_deploy:
    jobs:
      - check_whitespace
      - prettier
      - build
      - check_exif_data
      - check_html:
          requires:
            - build
      - publish_draft:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
